dist: focal
sudo: required
language: python
cache:
  pip: true
  apt: true

services:
  - postgresql
  - rabbitmq

python:
  - 3.6
  - 3.8

env:
  - DB_NAME=warehouse DB_USER=warehouse_user DB_PASSWORD=warehouse_password DB_HOST=db

before_install:
  # increase /var/ramfs size
  - sudo mount -o remount,size=50% /var/ramfs

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - sudo systemctl restart postgresql@9.6-main

before_script:
  - psql -tc 'SHOW server_version'
  - psql -c 'CREATE ROLE warehouse_user;'
  - psql -c 'ALTER ROLE warehouse_user WITH SUPERUSER;'
  - psql -c 'ALTER ROLE warehouse_user WITH LOGIN;'
  - psql -c "ALTER ROLE warehouse_user PASSWORD 'warehouse_pass';"
  - psql -c 'CREATE DATABASE warehouse_db OWNER warehouse_user;'

script:
  python runtests.py
