# Generated by Django 2.2.24 on 2021-09-06 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bar_code', models.CharField(max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('updated', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.Producer')),
            ],
            options={
                'unique_together': {('producer', 'name')},
            },
        ),
    ]
